// DEFINE A STRUCTURE EMPLOYEE WITH MEMBERS EMPLOYEE NAME, BASIC SALARY, ALLOWANCE. WRITE A FUNCTION TO CALCULATE IT'S GROSS SALARY AND NET SALARY.

#include <stdio.h>

struct employee
{
    char name[20];
    
}

int main()
{

}