# DISPLAYING NUMBERS FROM 1 TO 100 IN A PROPER FORMAT

# WE NEED TO DISPLAY EACH NUMBER IN A COLUMN WITH FIXED SIZE SO THAT THE OUTPUT WILL LOOK NICE.
# FOR THIS PURPOSE, WE CAN PECIFY COLUMN SIZE USING REPLACEMENT FIELD {} AND FORMAT() METHOD AS

#       print('{:8};.format(x*y), end = ' ')

# HERE, {:8} REPRESENTS THAT THE PRODUCE VALUE ( X*Y ) SHOULD BE DISPLAYED IN THE FILED SIZE OF


for x in range(1, 11):
    for y in range(1, 11):
        print('{:8}'.format(x*y), end = ' ') # EACH COLUMN SIZE IS 8
    print()
