# WAP IN PYTHON TO ADD TWO NUMBERS
# WAP IN PYTHON TO CALCULATE AREA AND PERIMETRE OF A CIRCLE
# WAP IN PYTHON TO CALCULATE AREA AND PERIMETER OF A CIRCLE

n1 = int(input("ENTER A NUMBER : "))
n2 = int(input("ENTER SECOND NUMBER : "))

sum = n1 + n2
         
print("SUM IS : ", sum)
