#include <iostream>
using namespace std;

int main()
{
	// NAMED STRUCTURES 

	// BY GIVING THE NAME TO THE STRUCTURE, YOU CAN TREAT IT AS A DATA TYPE. THIS MEANS THAT YOU CAN CREATE VARIABLES WITH THIS STRUCTURE ANY WHERE IN THE PROGRAM AT ANY TIME.

	// TO CREATE A NAMED STRUTURE, PUT THE NAME OF THE STRUCTURE RIGHT AFTER THE STRUCT KEYWORD

	struct myDataType { // THIS STRUCTURE IS NAMED "myDataType"
		int myNum;
		string myString;
	};

	// TO DECLARE A VARIABLE THAT USES THE STRUCTURE, USE THE NAME OF THE STRUCTURE AS THE DATA TYPE OF THE VARIABLE.

	myDataType myVar;


	return 0;
}
