#include <iostream>
using namespace std;

int main()
{
	// MEMORY ADDRESS
	
	/* 
	IN THE EXAMPLE FROM THE PREVIOUS PROGRAM, THE & OPERATOR WAS USED TO CREATE A REFERENCE VARIABLE. BUT IT CAN ALSO BE USED TO GET THE MEMORY ADDRESS OF A VARIABLE; WHICH IS THE LOCATION OF WHERE THE VARIABLE IS STORED ON THE COMPUTER.

	WHEN A VARIABLE IS CREATED IN C++, A MEMORY ADDRESS IS ASSIGNED TO THE VARIABLE, AND WHEN WE ASSIGN A VALUE TO THE VARIABLE, IT IS STORED IN THIS MEMORY ADDRESS.

	TO ACCESS IT, USE THE & OPERATOR, AND THE RESULT WILL REPRESENT WHERE THE VARIABLE IS STORED.

	*/

	string food = "Pizza";
	cout << &food; // outputs the address of the variable food.
	
	return 0;
}
