// ACCESS SPECIFIERS 

// BY NOW, YOU ARE QUITE FAMILIAR WITH THE public KEYWORD THAT APPEARS IN ALL OF OUR CLASS EXAMPLES.

class MyClass	// The class
{		
	public:	// Access Specifier
		// class members goes here
};



/* 

	THE public KEYWORD IS AN ACCESS SPECIFIER. ACCEESS SPECIFIERS DEFINE HOW THE MEMEBERS (ATTRIBUTES AND METHODS ) OF A CLASS CAN BE ACCESSED. IN THE EXAMPLE ABOVE, THE MEMBERS ARE public- WHICH MEANS THAT THEY CAN BE ACCESSED AND MODIFIED FROM OUTSIDE THE CODE.

	HOWEVER, WHAT IF WE WANT MEMBERS TO BE PRIVATE AND HIDDEN FROM THE OUTSIDE WORLD?

	IN C++, THERE ARE THREE ACCESS SPECIFIERS :
		-> public : MEMBERS ARE ACCESSIBLE FROM OUTSIDE THE CLASS 
		-> private : MEMBERS CANNOT BE ACCESSED (OR VIEWED) FROM OUTSIDE THE CLASS
		-> protected : MEMBERS CANNOT BE ACCESSED FROM OUTSIDE THE CLASS, HOWEVER, THEY CAN BE ACCESSED IN INHERITED CLASSES. 

